apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - "deployment.yaml"
configurations:
  - ""
images:
  - name: buildbot-worker
    newName: buildbot/buildbot-worker
    newTag: latest
configMapGenerator:
  - name: buildbot.tac
    files:
      - "buildbot.tac"
