apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - "deployment.yaml"
  - "service.yaml"
images:
  - name: buildbot
    newName: buildbot/buildbot-master
    newTag: latest
  - name: postgres
    newName: postgres
    newTag: "9.4"
configMapGenerator:
  - name: buildbot.tac
    files:
      - "buildbot.tac"
